version: "3.7"
services:
  db:
    container_name: postgresql_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=${PGDATA}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: "unless-stopped"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PIPENV_DONT_LOAD_ENV=1
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data:
  pgadmin-data:
