# Generated by Django 3.2.14 on 2022-07-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=9, unique=True, verbose_name='Nit')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_server', models.CharField(max_length=255, unique=True, verbose_name='Ip servidor')),
                ('name_server', models.CharField(max_length=255, verbose_name='Nombre Servidor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.client')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=255, verbose_name='Nombre servicio')),
                ('capacity', models.IntegerField()),
                ('use', models.IntegerField()),
                ('percent', models.IntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.server')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
