# Generated by Django 3.2.14 on 2022-07-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nit',
            field=models.CharField(max_length=9, unique=True, verbose_name='Nit'),
        ),
    ]
