# Generated by Django 3.2.14 on 2022-07-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_client_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_server', models.CharField(max_length=255, verbose_name='Ip servidor')),
                ('name_server', models.CharField(max_length=255, verbose_name='Nombre Servidor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.client')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
    ]
