# Generated by Django 3.2.14 on 2022-07-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='cliente',
            new_name='client',
        ),
    ]
