# Generated by Django 3.2.14 on 2022-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_rename_cliente_server_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip_server',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ip servidor'),
        ),
    ]
